// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yzmkgxypyjnylrtnefrp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl6bWtneHlweWpueWxydG5lZnJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMDE5MDEsImV4cCI6MjA2ODU3NzkwMX0.eLT5AybJFA8CstVO3-uEvnOGnoCm2L1UeB6IR1__aHk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});